stages:
  - docker
  - deploy

docker-build-and-ship:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: docker
  only:
    - main
  before_script:
    - echo "$SCW_KEY" | docker login rg.fr-par.scw.cloud/composecraft -u nologin --password-stdin
    - docker info
  script:
    - docker build -t rg.fr-par.scw.cloud/composecraft/composecraft:latest .
    - docker push rg.fr-par.scw.cloud/composecraft/composecraft:latest

redeploy-coolify:
  image: alpine/curl
  stage: deploy
  only:
    - main
  script:
      - |
          curl https://coolify.composecraft.com/api/v1/deploy\?uuid\=uos8wc0ogwcoo4k00gkkwkw8\&force\=false \
          -H "Authorization: Bearer ${COOLIFY_API_KEY}"

cloudflare-purge-cache:
  image: alpine/curl
  needs:
    - redeploy-coolify
  stage: deploy
  only:
    - main
  script:
      - |
          curl ${CLOUDFLARE_URL}