name: Bug Report
description: Report an issue with the application.
labels: bug
body:
  - type: dropdown
    attributes:
      label: Is the instance self-hosted or cloud?
      description: Indicate if you are using a self-hosted instance or the cloud version.
      options:
        - Self-hosted
        - Cloud
      required: true
  - type: input
    attributes:
      label: Which browser do you use?
      description: Specify the browser you were using (e.g., Chrome, Firefox, Safari).
      placeholder: e.g., Chrome 118.0
      required: true
  - type: input
    attributes:
      label: What OS do you use?
      description: Specify your operating system (e.g., Windows 11, macOS 14, Ubuntu 22.04).
      placeholder: e.g., Ubuntu 22.04
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a detailed description of the issue, including steps to reproduce it.
      placeholder: Include what you expected to happen and what actually happened.
      required: true
  - type: textarea
    attributes:
      label: Environment variables (non-sensitive)
      description: List the environment variables you use (excluding sensitive ones such as secrets or tokens).
      placeholder: e.g., NODE_ENV=production, ENABLE_FEATURE_X=true
      required: false
