name: Docker Image Push

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        workflow: docker-image.yml
        workflow_conclusion: success
        name: composecraft-docker-image

    - name: Load Docker image from artifact
      run: docker load -i composecraft-latest.tar

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker tag composecraft:latest ${{ secrets.DOCKER_USERNAME }}/composecraft:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/composecraft:latest
